site_name: AsyncMonolith Docs
site_url: https://timmoth.github.io/AsyncMonolith/
site_description: Lightweight asynchronous processes and scheduling.
site_author: Timmoth
repo_url: https://github.com/Timmoth/AsyncMonolith/
edit_uri: edit/main/docs

theme:
  name: readthedocs
  highlightjs: true
  logo: assets/logo.png
  hljs_languages:
    - csharp
nav:
  - Overview âœ…: index.md
  - Quick start â–¶ï¸: quickstart.md
  - Internals ğŸ§ : internals.md
  - Releases ğŸ“’: releases.md
  - Warnings âš ï¸: warnings.md
  - Support ğŸ›Ÿ: support.md
  - Demo App âœ¨: demo.md
  - Contributing ğŸ™: contributing.md
  - Tests ğŸ: tests.md
  - Guides:
      - Producing messages: guides/producing-messages.md
      - Scheduling messages: guides/scheduling-messages.md
      - Consuming messages: guides/consuming-messages.md
      - Changing messages: guides/changing-messages.md
      - Opentelemetry: guides/opentelemetry.md

  - Posts:
      - What is the Transactional Outbox?: posts/transactional-outbox.md
      - What is the Mediator pattern?: posts/mediator.md
      - What is Idempotency?: posts/idempotency.md

markdown_extensions:
  - tables
