site_name: AsyncMonolith Docs
theme:
  name: mkdocs
  highlightjs: true
  logo: assets/logo.png
  hljs_languages:
    - csharp
nav:
  - Overview âœ…: index.md
  - Quick start â–¶ï¸: quickstart.md
  - Guide ğŸ“¨: guide.md
  - Internals: internals.md
  - Releases ğŸ“’: releases.md
  - Warnings âš ï¸: warnings.md
  - Support ğŸ›Ÿ: support.md
  - Demo App: demo.md
  - Contributing ğŸ™: contributing.md
  - Tests ğŸ: tests.md

markdown_extensions:
  - tables
